"""initial

Revision ID: 6bba1057aa9a
Revises: 
Create Date: 2026-03-29 18:41:53.942099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6bba1057aa9a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('nfl_team', sa.String(), nullable=True),
    sa.Column('sleeper_id', sa.String(), nullable=True),
    sa.Column('espn_id', sa.String(), nullable=True),
    sa.Column('espn_athlete_id', sa.String(), nullable=True),
    sa.Column('fp_name', sa.String(), nullable=True),
    sa.Column('injury_status', sa.String(), nullable=True),
    sa.Column('injury_detail', sa.Text(), nullable=True),
    sa.Column('last_updated', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clerk_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('approved_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('sleeper_username', sa.String(), nullable=True),
    sa.Column('sleeper_user_id', sa.String(), nullable=True),
    sa.Column('sleeper_league_id', sa.String(), nullable=True),
    sa.Column('espn_league_id', sa.Integer(), nullable=True),
    sa.Column('espn_s2', sa.String(), nullable=True),
    sa.Column('swid', sa.String(), nullable=True),
    sa.Column('weight_sleeper', sa.Float(), nullable=False),
    sa.Column('weight_espn', sa.Float(), nullable=False),
    sa.Column('weight_fp', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clerk_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('beat_writer_sentiment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('source_name', sa.String(), nullable=True),
    sa.Column('headline', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('sentiment', sa.String(), nullable=True),
    sa.Column('published_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('scraped_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('my_roster',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('acquisition_date', sa.Date(), nullable=True),
    sa.Column('is_starter', sa.Boolean(), nullable=False),
    sa.Column('slot', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'player_id')
    )
    op.create_table('news_history_context',
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('context_summary', sa.Text(), nullable=True),
    sa.Column('last_updated', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_table('player_adp_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('adp', sa.Float(), nullable=True),
    sa.Column('adp_stdev', sa.Float(), nullable=True),
    sa.Column('position_rank', sa.Integer(), nullable=True),
    sa.Column('overall_rank', sa.Integer(), nullable=True),
    sa.Column('recorded_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_historical_stats',
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=True),
    sa.Column('fantasy_pts_ppr', sa.Float(), nullable=True),
    sa.Column('fantasy_ppg_ppr', sa.Float(), nullable=True),
    sa.Column('targets', sa.Integer(), nullable=True),
    sa.Column('receptions', sa.Integer(), nullable=True),
    sa.Column('rec_yards', sa.Integer(), nullable=True),
    sa.Column('rec_td', sa.Integer(), nullable=True),
    sa.Column('carries', sa.Integer(), nullable=True),
    sa.Column('rush_yards', sa.Integer(), nullable=True),
    sa.Column('rush_td', sa.Integer(), nullable=True),
    sa.Column('pass_yards', sa.Integer(), nullable=True),
    sa.Column('pass_td', sa.Integer(), nullable=True),
    sa.Column('interceptions', sa.Integer(), nullable=True),
    sa.Column('snap_pct_avg', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('player_id', 'season')
    )
    op.create_table('player_news',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('headline', sa.Text(), nullable=False),
    sa.Column('news_body', sa.Text(), nullable=True),
    sa.Column('published_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('news_type', sa.String(), nullable=True),
    sa.Column('is_rostered', sa.Boolean(), nullable=True),
    sa.Column('analysis_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_stock_profile',
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('overall_direction', sa.String(), nullable=True),
    sa.Column('overall_magnitude', sa.String(), nullable=True),
    sa.Column('concern_level', sa.Integer(), nullable=True),
    sa.Column('concern_summary', sa.Text(), nullable=True),
    sa.Column('worry_score', sa.Integer(), nullable=True),
    sa.Column('combined_score', sa.Float(), nullable=True),
    sa.Column('bullish_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('bearish_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('adp_trend', sa.String(), nullable=True),
    sa.Column('adp_trend_delta', sa.Float(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('sentiment_label', sa.String(), nullable=True),
    sa.Column('sentiment_confidence', sa.Float(), nullable=True),
    sa.Column('news_volume', sa.String(), nullable=True),
    sa.Column('dominant_themes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sentiment_vs_stock', sa.String(), nullable=True),
    sa.Column('alignment_note', sa.Text(), nullable=True),
    sa.Column('contrarian_flag', sa.Boolean(), nullable=True),
    sa.Column('historical_context', sa.Text(), nullable=True),
    sa.Column('short_term_outlook', sa.Text(), nullable=True),
    sa.Column('long_term_outlook', sa.Text(), nullable=True),
    sa.Column('draft_recommendation', sa.String(), nullable=True),
    sa.Column('last_full_analysis', sa.TIMESTAMP(), nullable=True),
    sa.Column('last_news_update', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_table('projections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('sleeper_proj', sa.Float(), nullable=True),
    sa.Column('espn_proj', sa.Float(), nullable=True),
    sa.Column('fp_proj', sa.Float(), nullable=True),
    sa.Column('weighted_proj', sa.Float(), nullable=True),
    sa.Column('sources_used', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence_flag', sa.String(), nullable=True),
    sa.Column('last_updated', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tracked_players',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('player_name', sa.String(), nullable=False),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('nfl_team', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('years_exp', sa.Integer(), nullable=True),
    sa.Column('depth_chart_pos', sa.String(), nullable=True),
    sa.Column('contract_year', sa.Boolean(), nullable=True),
    sa.Column('starred_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('star_notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'player_id')
    )
    op.create_table('news_analysis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('stock_direction', sa.String(), nullable=True),
    sa.Column('stock_magnitude', sa.String(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('short_term_impact', sa.Text(), nullable=True),
    sa.Column('long_term_impact', sa.Text(), nullable=True),
    sa.Column('context_notes', sa.Text(), nullable=True),
    sa.Column('contradictions_flagged', sa.Boolean(), nullable=True),
    sa.Column('contradiction_detail', sa.Text(), nullable=True),
    sa.Column('analysis_model', sa.String(), nullable=True),
    sa.Column('generated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['news_id'], ['player_news.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('news_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news_analysis')
    op.drop_table('tracked_players')
    op.drop_table('projections')
    op.drop_table('player_stock_profile')
    op.drop_table('player_news')
    op.drop_table('player_historical_stats')
    op.drop_table('player_adp_history')
    op.drop_table('news_history_context')
    op.drop_table('my_roster')
    op.drop_table('beat_writer_sentiment')
    op.drop_table('users')
    op.drop_table('players')
    # ### end Alembic commands ###
