"""add user_leagues table, remove sleeper_league_id

Revision ID: b8a500b02405
Revises: 6bba1057aa9a
Create Date: 2026-03-29 19:52:27.878025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8a500b02405'
down_revision: Union[str, Sequence[str], None] = '6bba1057aa9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_leagues',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('league_id', sa.String(), nullable=False),
    sa.Column('league_name', sa.String(), nullable=True),
    sa.Column('total_rosters', sa.Integer(), nullable=True),
    sa.Column('season', sa.Integer(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('connected_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('users', 'espn_league_id')
    op.drop_column('users', 'sleeper_league_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sleeper_league_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('espn_league_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_table('user_leagues')
    # ### end Alembic commands ###
