"""add player_sentiment_history

Revision ID: f48a3bbc432e
Revises: b8a500b02405
Create Date: 2026-09-17 16:09:10.295464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f48a3bbc432e'
down_revision: Union[str, Sequence[str], None] = 'b8a500b02405'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_sentiment_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('sentiment_label', sa.String(), nullable=True),
    sa.Column('concern_level', sa.Integer(), nullable=True),
    sa.Column('worry_score', sa.Integer(), nullable=True),
    sa.Column('combined_score', sa.Float(), nullable=True),
    sa.Column('overall_direction', sa.String(), nullable=True),
    sa.Column('recorded_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_sentiment_history_player_id'), 'player_sentiment_history', ['player_id'], unique=False)
    op.create_index(op.f('ix_player_sentiment_history_recorded_at'), 'player_sentiment_history', ['recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_sentiment_history_recorded_at'), table_name='player_sentiment_history')
    op.drop_index(op.f('ix_player_sentiment_history_player_id'), table_name='player_sentiment_history')
    op.drop_table('player_sentiment_history')
    # ### end Alembic commands ###
